<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="sd-aa56-6ff1" name="testcases.Sanity" tests="35" failures="3" timestamp="27 Sep 2018 08:26:53 GMT" time="870.857" errors="0">
  <testcase name="SanityTC34" time="16.538" classname="testcases.Sanity"/>
  <testcase name="SanityTC6" time="16.902" classname="testcases.Sanity"/>
  <testcase name="SanityTC24" time="25.403" classname="testcases.Sanity"/>
  <testcase name="SanityTC32" time="16.415" classname="testcases.Sanity"/>
  <testcase name="SanityTC19" time="60.060" classname="testcases.Sanity"/>
  <testcase name="SanityTC25" time="15.652" classname="testcases.Sanity"/>
  <testcase name="SanityTC8" time="23.141" classname="testcases.Sanity"/>
  <testcase name="SanityTC15" time="15.232" classname="testcases.Sanity"/>
  <testcase name="SanityTC35" time="16.395" classname="testcases.Sanity"/>
  <testcase name="SanityTC27" time="16.359" classname="testcases.Sanity"/>
  <testcase name="SanityTC33" time="17.508" classname="testcases.Sanity"/>
  <testcase name="SanityTC30" time="26.010" classname="testcases.Sanity"/>
  <testcase name="SanityTC2" time="72.909" classname="testcases.Sanity">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at utility.SeleniumUtils.waitForElementPresent(SeleniumUtils.java:565)
	at pageobjects.HomePage.filtersCheck(HomePage.java:80)
	at testcases.Sanity.SanityTC2(Sanity.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </failure>
  </testcase> <!-- SanityTC2 -->
  <testcase name="SanityTC18" time="26.384" classname="testcases.Sanity"/>
  <testcase name="SanityTC20" time="14.820" classname="testcases.Sanity"/>
  <testcase name="SanityTC31" time="16.818" classname="testcases.Sanity"/>
  <testcase name="SanityTC28" time="17.643" classname="testcases.Sanity"/>
  <testcase name="SanityTC26" time="25.203" classname="testcases.Sanity"/>
  <testcase name="SanityTC23" time="24.789" classname="testcases.Sanity"/>
  <testcase name="SanityTC17" time="42.185" classname="testcases.Sanity">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at utility.SeleniumUtils.waitForElementPresent(SeleniumUtils.java:550)
	at pageobjects.HomePage.checkLevel(HomePage.java:210)
	at testcases.Sanity.SanityTC17(Sanity.java:347)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </failure>
  </testcase> <!-- SanityTC17 -->
  <testcase name="SanityTC12" time="29.146" classname="testcases.Sanity"/>
  <testcase name="SanityTC7" time="18.190" classname="testcases.Sanity"/>
  <testcase name="SanityTC3" time="16.464" classname="testcases.Sanity"/>
  <testcase name="SanityTC11" time="24.178" classname="testcases.Sanity"/>
  <testcase name="SanityTC29" time="86.484" classname="testcases.Sanity">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at utility.SeleniumUtils.waitForElementPresent(SeleniumUtils.java:550)
	at pageobjects.HomePage.topExposuresPopupCheck(HomePage.java:106)
	at testcases.Sanity.SanityTC29(Sanity.java:563)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </failure>
  </testcase> <!-- SanityTC29 -->
  <testcase name="SanityTC9" time="17.257" classname="testcases.Sanity"/>
  <testcase name="SanityTC4" time="19.507" classname="testcases.Sanity"/>
  <testcase name="SanityTC1" time="26.083" classname="testcases.Sanity"/>
  <testcase name="SanityTC13" time="14.453" classname="testcases.Sanity"/>
  <testcase name="SanityTC5" time="27.969" classname="testcases.Sanity"/>
  <testcase name="SanityTC21" time="15.299" classname="testcases.Sanity"/>
  <testcase name="SanityTC22" time="15.182" classname="testcases.Sanity"/>
  <testcase name="SanityTC10" time="14.220" classname="testcases.Sanity"/>
  <testcase name="SanityTC14" time="14.836" classname="testcases.Sanity"/>
  <testcase name="SanityTC16" time="25.223" classname="testcases.Sanity"/>
</testsuite> <!-- testcases.Sanity -->
